apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: ai-marketplace
  labels:
    app: web
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
